version: "3"

services:  
  docs:
    build: .
    command: python3 serve.py
    volumes:
      - ".:/app/"
    ports:
      - "35730:35730"
      - "8001:8001"

  vale:
    image: jdkato/vale
    volumes:
      - "${PWD}/styles:/styles"
      - "${PWD}:/docs"
    working_dir: /docs
