version: "3"

services:
  docs:
    build: docs
    command: poetry run sphinx-autobuild --host 0.0.0.0 /app /app/_build
    volumes:
      - "${PWD}:/app/"
    ports:
      - "35730:35730"
      - "8000:8000"

  vale:
    image: jdkato/vale
    volumes:
      - "${PWD}:/docs"
    working_dir: /docs
