name: Update translations
on:
  pull_request:
    branches:
      - main
      - v5

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3
      - name: Run translation script
        run: ./.github/scripts/translations.sh
        shell: bash
