name: Update translations
on: [pull_request]

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - name: Run translation script
        run: ./.github/scripts/translations.sh
        shell: bash
