name: Update translations
on:
  push:
    branches:
      - main
      - v5
  pull_request:
    branches:
      - main
      - v5

jobs:
  translations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    env:
      CI_COMMIT_MESSAGE: Update translations
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install
      - run: ./.github/scripts/translations.sh
      - name: Commit translations
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add locale
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
